cf_postgres:
    driver: postgres
    open: host='$DB_HOST' port=$DB_PORT user='$DB_USER' password='$DB_PASSWORD' dbname='$DB_DATABASE_NAME' sslmode='disable'
cf_mysql:
    driver: mysql
    open: $DB_USER:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT)/$DB_DATABASE_NAME?parseTime=true
mariadb-development:
    driver: mysql
    open: stratos:strat0s@tcp(mariadb:3306)/stratos-db?parseTime=true
mariadb-k8s:
    driver: mysql
    open: $DB_USER:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT)/$DB_DATABASE_NAME?parseTime=true
mariadb-dev:
    driver: mysql
    open: stratos:strat0s@tcp(127.0.0.1:3306)/stratosdb?parseTime=true
postgres-dev:
    driver: postgres
    open: host='127.0.0.1' port=5432 user='stratos' password='strat0s' dbname='stratosdb' sslmode='disable'