resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.4.2

resources:
- name: stratos-seronet-staging
  type: cf
  icon: cloud-upload
  source:
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    organization: ((cf.org))
    space: ((cf.space))
    skip_cert_check: false

- name: stratos-seronet-release
  type: git
  icon: github-face
  source:
    uri: git@github.com:seronet-project/stratos.git
    branch: v2-master
    depth: 5
    disable_ci_skip: false
    private_key: ((github-private-key))

- name: stratos-cf-v2-master
  type: git
  icon: github-face
  source:
    uri: https://github.com/cloudfoundry-incubator/stratos
    branch: v2-master
    depth: 30

- name: notify
  type: slack-notification
  icon: chat-alert
  source:
    url: ((slack-webhook))

- name: merge-timer
  type: time
  source:
    start: 1:30 AM
    stop: 2:30 AM
    location: Europe/Berlin

jobs:
- name: merge-stratos
  public: false
  serial_groups: ["stratos"]
  plan:
  - get: merge-timer
    trigger: true
  - get: stratos-cf-v2-master
#    trigger: true
  - get: stratos-seronet-release
  - task: merge-stratos
    config:
      platform: linux
      inputs:
      - name: stratos-seronet-release
      outputs:
      - name: stratos-seronet-release
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cflinuxfs3
      run:
        path: bash
        args:
        - -exc
        - |
          cd stratos-seronet-release
          git config user.email "concourse@sero.network"
          git config user.name "SeRoNet Concourse"
          git remote add stratos https://github.com/cloudfoundry-incubator/stratos.git
          git fetch stratos v2-master
          git merge --no-edit stratos/v2-master
  - put: stratos-seronet-release
    params:
      repository: stratos-seronet-release

- name : deploy-stratos
  public: false
  serial_groups: ["stratos"]
  plan:
    - get: stratos-seronet-release
      trigger: true
    - task: stratos-seronet-prebuild
      config:
        platform: linux
        inputs:
          - name: stratos-seronet-release
        outputs:
          - name: stratos-out
        image_resource:
          type: docker-image
          source:
            repository: node
            tag: 8.9.4
        run:
          user: root
          path: sh
          args:
          - -exc
          - |
            cp -R stratos-seronet-release/* stratos-out
            cd stratos-out
            npm install
            npm run prebuild-ui
            rm -rf dist
            rm -rf node_modules
    - put: stratos-seronet-staging
      params:
        manifest: stratos-out/manifest.yml
      on_success:
        put: notify
        params:
          text: "SeRoNet Stratos deployed."
